### ISSUE TITLE
Artifact found. Can you analyse the problem and optimize the network architecture?

### ISSUE THREAD

**Issue by splinter21** [Junshk/CinCGAN-pytorch#12]
![artifact](https://user-images.githubusercontent.com/26759495/71523222-0ee8cd00-2903-11ea-83f2-58c27df6873e.png)

The model is trained by the default option. The reconstructed img is in the "result" folder after 400 epoch trained.

**Comment by Hawk0826** [comment]
@splinter21 Hello, I'm trying to run this network, but I got the generated SR img with serious problem. I checked this img and found its value of all pixels were around 110.  Have you ever changed any options or codes to avoid this problem？
![image](https://user-images.githubusercontent.com/26559876/71989016-d4b8ed00-326b-11ea-82d8-a4175d90ef21.png)
