### ISSUE TITLE
Pretrained EDSR model 

### ISSUE THREAD

**Issue by fredlll** [Junshk/CinCGAN-pytorch#6]
Hi is the download link downloading the correct model? 
The names of the downloaded model is EDSR_x4.py insteand of EDSR_baseline_x4.pt as suggested in the code.

After I renamed the file. It seems the model dimension does not match. 

Traceback (most recent call last):
  File "/home/shitaili/workspace/jupyter_notebooks/sr/CinCGAN-pytorch/code/model/edsr.py", line 65, in load_state_dict
    own_state[name].copy_(param)
RuntimeError: The expanded size of the tensor (64) must match the existing size (256) at non-singleton dimension 0.  Target sizes: [64, 3, 3, 3].  Tensor sizes: [256, 3, 3, 3]

**Comment by fredlll** [comment]
Okay I realized I should use the setting of this line from demo.sh :

EDSR in the paper (x4) - from EDSR (x2)

**Comment by AbdelsalamHaa** [comment]
Hi @fredlll  I'm facing the same issue, but I  can't find a file named demo.sh
